AllCops:
  Exclude:
    - 'bin/**'
    - 'db/**/*'
Style/Documentation:
  Exclude:
    - 'app/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'config/**/*'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
    '%i': '[]'

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

# Sequel defines select, disable cop to allow legitimate uses
Performance/Detect:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

MetricS/AbcSize:
  Max: 20

Style/CyclomaticComplexity:
  Max: 20

